 import Image1 from "./assets/1.jpg"
 import Image3 from "./assets/3.jpg"
 import Image4 from "./assets/4.jpg"
 import Image2 from "./assets/2.jpg"
 import Image5 from "./assets/5.jpg"
 import Image6 from "./assets/6.jpg"
 import Image7 from "./assets/7.jpg"
 import Image8 from "./assets/8.jpg"
 import Image9 from "./assets/9.jpg"
 import Image10 from "./assets/10.jpg"
 import Image11 from "./assets/11.jpg"
 import Image12 from "./assets/12.jpg"
 import Image13 from "./assets/13.jpg"
 import Image14 from "./assets/14.jpg"
 import Image15 from "./assets/s1.webp"
 import Image16 from "./assets/s2.webp"
 import Image17 from "./assets/s3.jpg"
 import Image18 from "./assets/s4.jpg"
 import Image19 from "./assets/s5.jpg"
 import Image20 from "./assets/s6.jpg"


 const items=[
    {    
      "id":1,
      "img":Image1,
      "name":"Canon EOS",
      "price":4235,
      "isInCart":false,
      "isInOrder":false,
      "isColod":false,
      "typeOfItem":"camera"  ,
      "totalQuantity":3,
    },
    {   "id":2,
        "img":Image2,
        "name":"Nikon DSLR",
        "price":535,
        "isInCart":false,
        "isInOrder":false ,
        "isColod":false,
        "typeOfItem":"camera",
        "totalQuantity":3,  
      },
      {   "id":3,
        "img":Image3,
        "name":"Sony DSLR",
        "price":457364 ,
        "isInCart":false,
        "isInOrder":true,
        "isColod":false ,
        "typeOfItem":"camera", 
        "totalQuantity":3,
      },
      {   "id":4,
        "img":Image4,
        "name":"Olympus DSLR, ",
        "totalQuantity":3,
        "price":4235 ,
        "isInCart":false,
        "isInOrder" :false, 
        "isColod":false,
        "typeOfItem":"camera",
        "totalQuantity":3,
      },
      {   "id":5,
          "img":Image5,
          "name":"Titan Model #301",
          "price":535 ,
          "isInCart":false,
          "isInOrder" :false,
          "isColod":false ,
          "typeOfItem":"camera",
          "totalQuantity":3,
        },
        {   "id":6,
          "img":Image6,
          "name":"Titan Model #201",
          "price":457364 ,
          "isInCart":false,
          "isInOrder":false ,
          "isColod":false ,
          "typeOfItem":"cloth", 
          "totalQuantity":3,

        },
        {   "id":7,
          "img":Image7 ,         
          "name":"HMT Milan",
          "price":4235  ,
          "isInCart":false,
          "isInOrder":false ,
          "isColod":false,
          "typeOfItem":"watch", 
          "totalQuantity":3,

        },
        {   "id":8,
            "img":Image8,
            "name":"Faber Luba",
            "price":535 ,
            "isInCart":false,
            "isInOrder":false,
            "isColod":false ,
            "typeOfItem":"cloth",
            "totalQuantity":3, 
          },
          {   "id":9,
            "img":Image9,
            "name":"H&W ",
            "price":457364 ,
            "isInCart":false,
            "isInOrder" :false,
            "isColod":false ,
            "typeOfItem":"watch",
            "totalQuantity":3,
          },
          {   "id":10,
            "img":Image10,
            "name":"Luis Phil ",
            "price":535 ,
            "isInCart":false,
            "isInOrder" :false,
            "isColod":false ,
            "typeOfItem":"watch",
            "totalQuantity":3,
          },
          {   "id":11,
            "img":Image11,
            "name":"John Zok ",
            "price":457364,
            "isInOreder":false,
            "isInCart":false,  
            "isColod":false ,
            "typeOfItem":"watch",
            "totalQuantity":3,
          },
          {   "id":12,
            "img":Image12,         
            "name":"mac PC",
            "price":4235 ,
            "isInOreder":false,
            "isInCart":false, 
            "typeOfItem":"watch", 
            "totalQuantity":3,
          },
          {   "id":13,
              "img":Image13,
              "name":"Jhalsani ",
              "price":535 ,
              "isInOreder":false,
              "isInCart":false,
              "isColod":false ,
              "typeOfItem":"cloth",
              "totalQuantity":3, 
 
            },
            {   "id":14,
              "img":Image14,
              "name":"mac PC",
              "price":457364,
              "isInOreder":false,
              "isInCart":false,
              "isColod":false ,
              "typeOfItem":"cloth",
              "totalQuantity":3, 
  
            },
            {   "id":15,
              "img":Image15,
              "name":"Faber Luba",
              "price":535 ,
              "isInOreder":false,
              "isInCart":false,
              "isColod":false ,
              "typeOfItem":"shoes",
              "totalQuantity":3, 
            },
            {   "id":16,
              "img":Image16,
              "name":"H&W ",
              "price":457364 ,
              "isInOreder":false,
              "isInCart":false, 
              "isColod":false ,
              "typeOfItem":"shoes",
              "totalQuantity":3,
            },
            {   "id":17,
              "img":Image17,
              "name":"Luis Phil ",
              "price":535,
              "isInOreder":false,
              "isInCart":false, 
              "isColod":false,
              "typeOfItem":"shoes",
              "totalQuantity":3,
            },
            {   "id":18,
              "img":Image18,
              "name":"John Zok ",
              "price":457364,
              "isInOreder":false,
              "isInCart":false, 
              "isColod":false,
              "typeOfItem":"shoes", 
              totalQuantity:4, 
            },
            {   "id":19,
              "img":Image19 ,         
              "name":"shoes2",
              "price":4235 ,
              "isInOreder":false,
              "isInCart":false, 
              "isColod":false ,
              "typeOfItem":"shoes",
              "totalQuantity":4,
            },
            {   "id":20,
                "img":Image20,  
                "name":"shoes ",
                "price":535,
                "isInOreder":false,
                "isInCart":false, 
                "isColod":false ,
                "typeOfItem":"shoes",
                "totalQuantity":4, 
              },
             
]
export default items